<?php

namespace ContainerJjpbA6B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3MnwcCtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3MnwcCt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3MnwcCt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\LampadaireController::citizenIndex' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LampadaireController::citizenShow' => ['privates', '.service_locator.65zMX0k', 'get_ServiceLocator_65zMX0kService', true],
            'App\\Controller\\LampadaireController::delete' => ['privates', '.service_locator.gSX6PK9', 'get_ServiceLocator_GSX6PK9Service', true],
            'App\\Controller\\LampadaireController::edit' => ['privates', '.service_locator.gSX6PK9', 'get_ServiceLocator_GSX6PK9Service', true],
            'App\\Controller\\LampadaireController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LampadaireController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LampadaireController::show' => ['privates', '.service_locator.65zMX0k', 'get_ServiceLocator_65zMX0kService', true],
            'App\\Controller\\QuartierController::delete' => ['privates', '.service_locator.QmwNuCG', 'get_ServiceLocator_QmwNuCGService', true],
            'App\\Controller\\QuartierController::edit' => ['privates', '.service_locator.QmwNuCG', 'get_ServiceLocator_QmwNuCGService', true],
            'App\\Controller\\QuartierController::index' => ['privates', '.service_locator.83faU9g', 'get_ServiceLocator_83faU9gService', true],
            'App\\Controller\\QuartierController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\QuartierController::show' => ['privates', '.service_locator.LYufiel', 'get_ServiceLocator_LYufielService', true],
            'App\\Controller\\QuartierController::showAll' => ['privates', '.service_locator.83faU9g', 'get_ServiceLocator_83faU9gService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\LampadaireController:citizenIndex' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LampadaireController:citizenShow' => ['privates', '.service_locator.65zMX0k', 'get_ServiceLocator_65zMX0kService', true],
            'App\\Controller\\LampadaireController:delete' => ['privates', '.service_locator.gSX6PK9', 'get_ServiceLocator_GSX6PK9Service', true],
            'App\\Controller\\LampadaireController:edit' => ['privates', '.service_locator.gSX6PK9', 'get_ServiceLocator_GSX6PK9Service', true],
            'App\\Controller\\LampadaireController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LampadaireController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LampadaireController:show' => ['privates', '.service_locator.65zMX0k', 'get_ServiceLocator_65zMX0kService', true],
            'App\\Controller\\QuartierController:delete' => ['privates', '.service_locator.QmwNuCG', 'get_ServiceLocator_QmwNuCGService', true],
            'App\\Controller\\QuartierController:edit' => ['privates', '.service_locator.QmwNuCG', 'get_ServiceLocator_QmwNuCGService', true],
            'App\\Controller\\QuartierController:index' => ['privates', '.service_locator.83faU9g', 'get_ServiceLocator_83faU9gService', true],
            'App\\Controller\\QuartierController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\QuartierController:show' => ['privates', '.service_locator.LYufiel', 'get_ServiceLocator_LYufielService', true],
            'App\\Controller\\QuartierController:showAll' => ['privates', '.service_locator.83faU9g', 'get_ServiceLocator_83faU9gService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\LampadaireController::citizenIndex' => '?',
            'App\\Controller\\LampadaireController::citizenShow' => '?',
            'App\\Controller\\LampadaireController::delete' => '?',
            'App\\Controller\\LampadaireController::edit' => '?',
            'App\\Controller\\LampadaireController::index' => '?',
            'App\\Controller\\LampadaireController::new' => '?',
            'App\\Controller\\LampadaireController::show' => '?',
            'App\\Controller\\QuartierController::delete' => '?',
            'App\\Controller\\QuartierController::edit' => '?',
            'App\\Controller\\QuartierController::index' => '?',
            'App\\Controller\\QuartierController::new' => '?',
            'App\\Controller\\QuartierController::show' => '?',
            'App\\Controller\\QuartierController::showAll' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\LampadaireController:citizenIndex' => '?',
            'App\\Controller\\LampadaireController:citizenShow' => '?',
            'App\\Controller\\LampadaireController:delete' => '?',
            'App\\Controller\\LampadaireController:edit' => '?',
            'App\\Controller\\LampadaireController:index' => '?',
            'App\\Controller\\LampadaireController:new' => '?',
            'App\\Controller\\LampadaireController:show' => '?',
            'App\\Controller\\QuartierController:delete' => '?',
            'App\\Controller\\QuartierController:edit' => '?',
            'App\\Controller\\QuartierController:index' => '?',
            'App\\Controller\\QuartierController:new' => '?',
            'App\\Controller\\QuartierController:show' => '?',
            'App\\Controller\\QuartierController:showAll' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
