<?php

namespace ContainerJjpbA6B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QmwNuCGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QmwNuCG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QmwNuCG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'quartier' => ['privates', '.errored..service_locator.QmwNuCG.App\\Entity\\Quartier', NULL, 'Cannot autowire service ".service_locator.QmwNuCG": it needs an instance of "App\\Entity\\Quartier" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'quartier' => 'App\\Entity\\Quartier',
        ]);
    }
}
