<?php

namespace ContainerJjpbA6B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_65zMX0kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.65zMX0k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.65zMX0k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lampadaire' => ['privates', '.errored..service_locator.65zMX0k.App\\Entity\\Lampadaire', NULL, 'Cannot autowire service ".service_locator.65zMX0k": it needs an instance of "App\\Entity\\Lampadaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lampadaire' => 'App\\Entity\\Lampadaire',
        ]);
    }
}
