<?php

namespace ContainerJjpbA6B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLampadaire2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gSX6PK9.App\Entity\Lampadaire' shared service.
     *
     * @return \App\Entity\Lampadaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gSX6PK9": it needs an instance of "App\\Entity\\Lampadaire" but this type has been excluded in "config/services.yaml".');
    }
}
