<?php

namespace ContainerFNSWAas;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLampadaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.65zMX0k.App\Entity\Lampadaire' shared service.
     *
     * @return \App\Entity\Lampadaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.65zMX0k": it needs an instance of "App\\Entity\\Lampadaire" but this type has been excluded in "config/services.yaml".');
    }
}
